;; *************** macroList.asm ***************
;; MacroList export. Saturday, April 25, 2020 6:47:15 PM

  .include ROOT\System\Macros\AddValue.asm
  .include ROOT\System\Macros\AssignHudLabel.asm
  .include ROOT\System\Macros\AssignHudVariable.asm
  .include ROOT\System\Macros\AssignHudVariableImage.asm
  .include ROOT\System\Macros\BeginFade.asm
  .include ROOT\System\Macros\BlackOutArea.asm
  .include ROOT\System\Macros\ChangeAllTiles.asm
  .include ROOT\System\Macros\ChangeAllTilesDirect.asm
  .include ROOT\System\Macros\ChangeBank.asm
  .include ROOT\System\Macros\ChangeObjectState.asm
  .include ROOT\System\Macros\ChangeTile.asm
  .include ROOT\System\Macros\ChangeTileAtCollision.asm
  .include ROOT\System\Macros\CheckForHorizontalCollision.asm
  .include ROOT\System\Macros\CheckForVerticalEjection.asm
  .include ROOT\System\Macros\CheckPlayerCameraPosition.asm
  .include ROOT\System\Macros\CheckPotentialPosition.asm
  .include ROOT\System\Macros\CheckPotentialPositionSafe.asm
  .include ROOT\System\Macros\CheckPotentialPositionScroll.asm
  .include ROOT\System\Macros\CheckScrollColumnForNewMonsters.asm
  .include ROOT\System\Macros\CheckTopLayer.asm
  .include ROOT\System\Macros\CheckUnderObject.asm
  .include ROOT\System\Macros\ContinueText.asm
  .include ROOT\System\Macros\CountObjects.asm
  .include ROOT\System\Macros\CreateObject.asm
  .include ROOT\System\Macros\DeactivateCurrentObject.asm
  .include ROOT\System\Macros\DeactivateTargetObject.asm
  .include ROOT\System\Macros\DetermineCollisionTableOfPoints.asm
  .include ROOT\System\Macros\DoPlayerGuidedLeftScroll.asm
  .include ROOT\System\Macros\DoPlayerGuidedRightScroll.asm
  .include ROOT\System\Macros\DrawBox.asm
  .include ROOT\System\Macros\DrawSprite.asm
  .include ROOT\System\Macros\DrawText.asm
  .include ROOT\System\Macros\FaceDirection.asm
  .include ROOT\System\Macros\GetAbsoluteValue.asm
  .include ROOT\System\Macros\GetCurrentActionType.asm
  .include ROOT\System\Macros\GetScreenBank.asm
  .include ROOT\System\Macros\GetTrigger.asm
  .include ROOT\System\Macros\GetTriggerAtSeam.asm
  .include ROOT\System\Macros\GoToScreen.asm
  .include ROOT\System\Macros\HandleAimedPhysics.asm
  .include ROOT\System\Macros\HandleGravity.asm
  .include ROOT\System\Macros\HandleHorisontalInertia.asm
  .include ROOT\System\Macros\HandleVerticalInertia.asm
  .include ROOT\System\Macros\HideSprites.asm
  .include ROOT\System\Macros\HudUpdateForNumericDisplay.asm
  .include ROOT\System\Macros\InitializeColumnWrite.asm
  .include ROOT\System\Macros\LoadAttributeData.asm
  .include ROOT\System\Macros\LoadAttributes.asm
  .include ROOT\System\Macros\LoadBackgroundPalette.asm
  .include ROOT\System\Macros\LoadBackgroundPaletteLabel.asm
  .include ROOT\System\Macros\LoadChrData.asm
  .include ROOT\System\Macros\LoadCollisionTable.asm
  .include ROOT\System\Macros\LoadNametableFull.asm
  .include ROOT\System\Macros\LoadNametableMeta.asm
  .include ROOT\System\Macros\LoadScreen.asm
  .include ROOT\System\Macros\LoadSpritePalette.asm
  .include ROOT\System\Macros\MoveTowardsPoint.asm
  .include ROOT\System\Macros\PlaySong.asm
  .include ROOT\System\Macros\PlaySound.asm
  .include ROOT\System\Macros\PushVariableToValue.asm
  .include ROOT\System\Macros\ReturnToPrevBank.asm
  .include ROOT\System\Macros\SetAttributeToChange.asm
  .include ROOT\System\Macros\SetColumnTileUpdatePosition.asm
  .include ROOT\System\Macros\SetMetaTileToChange.asm
  .include ROOT\System\Macros\SetTileToChange.asm
  .include ROOT\System\Macros\ShowSprites.asm
  .include ROOT\System\Macros\StartMoving.asm
  .include ROOT\System\Macros\StopMoving.asm
  .include ROOT\System\Macros\StopSound.asm
  .include ROOT\System\Macros\SubtractValue.asm
  .include ROOT\System\Macros\TriggerScreen.asm
  .include ROOT\System\Macros\UpdateHud.asm
  .include ROOT\System\Macros\UpdateSpritePointer.asm
